#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#


module Color
  RED = 1
  YELLOW = 2
  GREEN = 3
  BLUE = 4
  VALUE_MAP = {1 => "RED", 2 => "YELLOW", 3 => "GREEN", 4 => "BLUE"}
  VALID_VALUES = Set.new([RED, YELLOW, GREEN, BLUE]).freeze
end

